### ISSUE TITLE
The plugin does not appear to be working.

### ISSUE THREAD

**Issue by Sylvie-Fluff** [nosoop/SM-CustomStatusHUD#2]
I am making a weapon that uses the "damage increase mult on hit" and the "weapon overheat" attributes from the [custom attribute starter pack](https://github.com/nosoop/SM-TFCustomAttributeStarterPack), and while they are both functioning as intended gameplay wise, there is no indicator on the HUD for either of them. I have the "show_on_hud" value set to 1 on the damage increase attribute. I should also say that I have "cl_hud_minmode" and "cl_hud_notification_duration" set to their base values, so that isn't the issue. Any advice on the issue would be appreciated.

**Comment by nosoop** [comment]
Hi &mdash; make sure the plugin is indeed loaded by running `sm plugins list` in the server console; since the Custom Status HUD plugin only provides forwards (no natives), it's not a strictly required dependency, and it not being present will not cause plugins that depend on it to fail to load.

If it is indeed loaded, review plugins created by other third-parties.  There are a limited number of text channels available for plugins to use; other plugins that display their own text may prevent the text element from consistently displaying.

If those seem okay I can provide a test plugin to output some text on screen via the API to verify that it's working.

**Comment by Sylvie-Fluff** [comment]
Ok, I have checked my plugin list and it is there, so it is installed, and the only plugins I currently have on my server are CWX and its various dependencies, none of which have constant text on the screen, so I doubt third-party plugins are the issue. I can try the test plugin.

**Comment by nosoop** [comment]
Sure; here you go.  The below plugin will output the current date / time from the server as one of the items.

[statushud-test.zip](https://github.com/nosoop/SM-CustomStatusHUD/files/9865665/statushud-test.zip)

**Comment by Sylvie-Fluff** [comment]
Ok I have installed and ran this plugin, and it does not appear to be working. Upon checking the plugin list the same way as before, it showed up, so it is installed, just not showing in-game. (I have also tried changing resolution but that solved nothing.) Perhaps a recent update could have messed with the plugin in some way?

**Comment by nosoop** [comment]
Nope; I wrote the plugin and confirmed it was working yesterday before replying with it attached.
Are you using a custom HUD?  This is starting to extend past my scope of knowledge, but the HUD element rendering text may be specified as a UI resource.  I don't see any references related to that in any files, however.

**Comment by Sylvie-Fluff** [comment]
Ok so I removed the entirety of my custom folder, hud included (which was Enhanced Default Hud), and that didn't work. I also tried changing the purity settings on the server, to no avail. At this point I don't know what it could be anymore. I'll keep trying to look into it because at this point I feel like it was probably an install mistake on my end, thank you for the help though.

**Comment by nosoop** [comment]
Per @Blunderstab's investigation, it looks like SourceMod may be overwriting cookies that it shouldn't; a failsafe has been added in case the value isn't correctly parsed.  Prior to the addition of the failsafe, the value would be left zeroed out and would render as completely invisible text.

I've cut a new release; please retest with the new build and reclose the issue if it's confirmed resolved.

**Comment by nosoop** [comment]
I'll assume this is resolved.  If you've revisited this and the issue is still present, feel free to reopen; if someone else runs into this issue on the latest release do post a new issue.
